name: Daily Master Merges Report

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get merge commits
        id: get_merges
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          TODAY=$(date -u +%Y-%m-%d)

          git checkout master

          git log --merges --since="$YESTERDAY 23:59" --until="$TODAY 23:59" \
            --pretty=format:"| %h | %an | %s |" > merge_log.txt

          if [[ ! -s merge_log.txt ]]; then
            echo "No merges today." > merge_log.txt
          else
            sed -i '1i| Commit | Author | Message |\n|--------|--------|---------|' merge_log.txt
          fi

          echo "MERGES<<EOF" >> $GITHUB_ENV
          cat merge_log.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MERGES: ${{ env.MERGES }}
        run: |
          jq -n \
            --arg text "*📌 Daily Merge Report to \`master\`*:\n```$MERGES```" \
            '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"