name: Daily Master Merges Report

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access full commit history

      - name: Get merge commits to master
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          TODAY=$(date -u +%Y-%m-%d)

          git checkout master

          git log --merges --since="$YESTERDAY 23:59" --until="$TODAY 23:59" \
            --pretty=format:"| %h | %an | %s |" > merge_log.txt

          if [[ ! -s merge_log.txt ]]; then
            echo "No merges today." > merge_log.txt
          else
            {
              echo "| Commit | Author | Message |"
              echo "|--------|--------|---------|"
              cat merge_log.txt
            } > formatted_log.txt
            mv formatted_log.txt merge_log.txt
          fi

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
        run: |
          MERGES=$(cat merge_log.txt)

          MESSAGE=$(printf "*📌 Daily Merge Report for \`$REPO\` → \`master\` branch*\n\`\`\`\n%s\n\`\`\`" "$MERGES")

          jq -n --arg text "$MESSAGE" '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"