name: Daily Master Commits Report (IST + PR Links in Column)

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate commit report with IST and PR links
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          TODAY=$(date -u +%Y-%m-%d)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          REPO_OWNER=${GITHUB_REPOSITORY%%/*}

          git checkout master

          export TZ=Asia/Kolkata

          echo "| Commit | Author | Time (IST) | Message | PR Link |" > commit_log.txt
          echo "|--------|--------|------------|---------|---------|" >> commit_log.txt

          git log --since="$YESTERDAY 23:59" --until="$TODAY 23:59" --date=format:'%Y-%m-%d %H:%M:%S' \
            --pretty=format:"%h|%an|%ad|%s" | while IFS='|' read -r sha author date msg; do
              pr_link=""

              if [[ "$msg" =~ Merge\ pull\ request\ \#([0-9]+) ]]; then
                pr_number="${BASH_REMATCH[1]}"
                pr_link="https://github.com/$REPO_OWNER/$REPO_NAME/pull/$pr_number"
              fi

              # Escape pipes in message to avoid breaking the table
              safe_msg=$(echo "$msg" | sed 's/|/\\|/g')

              echo "| $sha | $author | $date | $safe_msg | $pr_link |" >> commit_log.txt
          done

          if [[ $(wc -l < commit_log.txt) -le 2 ]]; then
            echo "No commits today." > commit_log.txt
          fi

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
        run: |
          COMMITS=$(cat commit_log.txt)

          MESSAGE=$(printf "*📌 Daily Commit Report for \`$REPO\` → \`master\` branch (IST)*\n\`\`\`\n%s\n\`\`\`" "$COMMITS")

          jq -n --arg text "$MESSAGE" '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"