name: Daily Master Commits Report

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure master branch
        run: git checkout master

      - name: Generate aligned commit table with PR Approvers (IST)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          REPO=${GITHUB_REPOSITORY}
          export TZ=Asia/Kolkata
          START_TIME=$(date -d '24 hours ago' --iso-8601=seconds)

          OUTPUT_FILE=commit_log.txt
          > $OUTPUT_FILE

          printf "| %-8s | %-18s | %-20s | %-18s | %-50s |\n" "Commit" "Author" "Time (IST)" "Approver(s)" "Message" >> $OUTPUT_FILE
          printf "|%s|\n" "$(printf '--------|--------------------|----------------------|--------------------|--------------------------------------------------')" >> $OUTPUT_FILE

          COMMITS_FOUND=0

          while read -r sha; do
            COMMITS_FOUND=1
            AUTHOR=$(git show -s --format='%an' $sha)
            DATE=$(git show -s --date=local --format='%ad' $sha)
            MSG=$(git show -s --format='%s' $sha | cut -c1-50 | tr -d '\n\r' | sed 's/|/‖/g')
            SHORT_SHA=$(echo "$sha" | cut -c1-8)

            PR_JSON=$(gh api /repos/$REPO/commits/$sha/pulls --jq '.[0]' || true)
            if [[ -n "$PR_JSON" ]]; then
              PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
              APPROVERS=$(gh api /repos/$REPO/pulls/$PR_NUMBER/reviews \
                | jq -r '[.[] | select(.state == "APPROVED") | .user.login] | unique | join(", ")')
              [[ -z "$APPROVERS" ]] && APPROVERS="—"
            else
              APPROVERS="—"
            fi

            printf "| %-8s | %-18s | %-20s | %-18s | %-50s |\n" "$SHORT_SHA" "$AUTHOR" "$DATE" "$APPROVERS" "$MSG"
          done < <(git log --since="$START_TIME" --format="%H")

          if [[ "$COMMITS_FOUND" -eq 0 ]]; then
            echo "No commits in the last 24 hours." > $OUTPUT_FILE
          fi

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
        run: |
          COMMITS=$(cat commit_log.txt)
          MESSAGE=$(printf "*📌 Daily Commit Report for \`$REPO\` → \`master\` branch (last 24h, IST)*\n\`\`\`\n%s\n\`\`\`" "$COMMITS")

          jq -n --arg text "$MESSAGE" '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"
