name: Daily Master Commits Report (IST + Clickable PR #)

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate commit report with IST + PR short links
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          TODAY=$(date -u +%Y-%m-%d)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          REPO_OWNER=${GITHUB_REPOSITORY%%/*}

          git checkout master
          export TZ=Asia/Kolkata

          echo "| Commit | Author | Time (IST) | Message |" > commit_log.txt
          echo "|--------|--------|------------|---------|" >> commit_log.txt
          > pr_links.txt

          git log --since="$YESTERDAY 23:59" --until="$TODAY 23:59" --date=format:'%Y-%m-%d %H:%M:%S' \
            --pretty=format:"%h|%an|%ad|%s" | while IFS='|' read -r sha author date msg; do
              pr_display=""
              if [[ "$msg" =~ Merge\ pull\ request\ \#([0-9]+) ]]; then
                pr_number="${BASH_REMATCH[1]}"
                pr_url="https://github.com/$REPO_OWNER/$REPO_NAME/pull/$pr_number"
                pr_display="#$pr_number"
                echo "$pr_display → <$pr_url>" >> pr_links.txt
              fi

              safe_msg=$(echo "$msg" | sed 's/|/\\|/g')
              echo "| $sha | $author | $date | $safe_msg |" >> commit_log.txt
          done

          if [[ $(wc -l < commit_log.txt) -le 2 ]]; then
            echo "No commits today." > commit_log.txt
          fi

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
        run: |
          TABLE=$(cat commit_log.txt)
          PRLINKS=$(cat pr_links.txt)

          MESSAGE=$(printf "*📌 Daily Commit Report for \`$REPO\` → \`master\` branch (IST)*\n\`\`\`\n%s\n\`\`\`\n\n*🔗 PR Links:*\n%s" "$TABLE" "$PRLINKS")

          jq -n --arg text "$MESSAGE" '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"