name: Daily Master Commits Report

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all commits to master in the last day
        run: |
          YESTERDAY=$(date -u -d "yesterday" +%Y-%m-%d)
          TODAY=$(date -u +%Y-%m-%d)

          git checkout master

          git log --since="$YESTERDAY 23:59" --until="$TODAY 23:59" \
            --pretty=format:"| %h | %an | %s |" > commit_log.txt

          if [[ ! -s commit_log.txt ]]; then
            echo "No commits today." > commit_log.txt
          else
            {
              echo "| Commit | Author | Message |"
              echo "|--------|--------|---------|"
              cat commit_log.txt
            } > formatted_log.txt
            mv formatted_log.txt commit_log.txt
          fi

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
        run: |
          COMMITS=$(cat commit_log.txt)

          MESSAGE=$(printf "*📌 Daily Commit Report for \`$REPO\` → \`master\` branch*\n\`\`\`\n%s\n\`\`\`" "$COMMITS")

          jq -n --arg text "$MESSAGE" '{text: $text}' \
            | curl -X POST -H 'Content-type: application/json' --data @- "$SLACK_WEBHOOK_URL"